"""EU AI Act compliance — transparency obligations (Article 52)."""

TRANSPARENCY_NOTICE = (
    "This response was generated by an AI system (HU AI Platform). "
    "The information provided may not be complete or fully accurate. "
    "For official information, please contact Hogeschool Utrecht directly."
)

TRANSPARENCY_NOTICE_NL = (
    "Dit antwoord is gegenereerd door een AI-systeem (HU AI Platform). "
    "De verstrekte informatie is mogelijk niet volledig of geheel nauwkeurig. "
    "Neem voor officiële informatie rechtstreeks contact op met Hogeschool Utrecht."
)


def add_transparency_notice(response: str, language: str = "en") -> str:
    """Append EU AI Act Article 52 transparency notice to a response."""
    notice = TRANSPARENCY_NOTICE_NL if language == "nl" else TRANSPARENCY_NOTICE
    return f"{response}\n\n---\n*{notice}*"


def get_system_disclosure() -> str:
    """Return the disclosure statement for system-level transparency."""
    return (
        "You are an AI assistant. Always disclose that you are an AI system when asked. "
        "Never pretend to be human. This is required by the EU AI Act (Article 52)."
    )
